# pull official base image
FROM node:latest

# set working directory
WORKDIR /app

# add `/app/node_modules/.bin` to $PATH
ENV PATH /app/node_modules/.bin:$PATH

# install app dependencies
COPY /react/package.json .
RUN npm install -g

COPY ./react/. .

# start app
CMD ["npm", "start"]