# Build environment
FROM node:latest as build
WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH
COPY /react/package.json .
COPY /react/package-lock.json .
RUN npm ci --silent
RUN npm install react-scripts@3.4.1 -g --silent
COPY ./react/. .
RUN npm run build

# Production environment
FROM nginx:latest
COPY --from=build /app/build /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
